groups:
 - name: Prometheus
   rules:
   - alert: TargetDown
     expr: avg(up) BY (job) < 1
     for: 1m
     labels:
       severity: warning
     annotations:
       description: '{{$labels.job}} target down'
       summary: 'target down'
